name: CI

on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        py: [ "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.py }} }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest
      - name: Tests
        run: pytest -q
